# Generated by Django 5.1.2 on 2024-11-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_product_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
